### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by slavikdenis** [suwu150/react-native-tree-select#10]
It would be great if we could add simple typescript typings. Would you accept a PR? :)

**Comment by suwu150** [comment]
> It would be great if we could add simple typescript typings. Would you accept a PR? :)

Yes, we accept pr

**Comment by slavikdenis** [comment]
I submitted the PR :) https://github.com/suwu150/react-native-tree-select/issues/10

Thanks

**Comment by slavikdenis** [comment]
Could this get released please? :)
