### ISSUE TITLE
yarn安装后，启动项目时报错：没安装react-native-vector-icons

### ISSUE THREAD

**Issue by okilled** [suwu150/react-native-tree-select#18]
单独安装react-native-vector-icons后启动项目正常（react-native run-android）

**Comment by suwu150** [comment]
> 单独安装react-native-vector-icons后启动项目正常（react-native run-android）

你需要手动安装这个库,其中使用的图标就是用这个库完成的

**Comment by suwu150** [comment]
@okilled 请问是怎么解决的?

**Comment by okilled** [comment]
手动安装（react-native-vector-icons）
